on:
  push:
    paths:
    - 'zmk-keymaps/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'zmk-keymaps/**'
    - '.github/workflows/**'
  workflow_dispatch:


jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: zmk-keymaps
